### ISSUE TITLE
[Bug] Ignores issues added by github-actions

### ISSUE THREAD

**Issue by stefankp** [actions/add-to-project#258]
This automation seems to ignore issues that are created by `github-action` bot, e.g. using this action https://github.com/marketplace/actions/create-an-issue.

**Comment by mattcosta7** [comment]
I could be wrong, but I believe this is expected behavior, and a limitation of actions, which try to avoid potentially recursive calls from workflows https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow

I think you should be able to get the url/number from the issue output from that action, and pipe it into a custom graphql call (likely as another step of that workflow, or a job that depends on it) using this action as a reference.
