### ISSUE TITLE
Is there any way to let Dependabot successfully trigger this action ?

### ISSUE THREAD

**Issue by teolemon** [actions/add-to-project#93]
I've created a PR to disable the action if the PR is created by Dependabot.
https://github.com/openfoodfacts/robotoff/pull/749

But I believe bots should be able to contribute ;-)
Is there any way to make it work ?

**Comment by angela-tran** [comment]
I saw that in [one of your Actions runs](https://github.com/openfoodfacts/robotoff/runs/6291593499?check_suite_focus=true) the log was showing `Error: Input required and not supplied: github-token`.

It seems this is because Dependabot is not allowed to read from GitHub secrets. (see https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/). 

The discussion on https://github.com/actions/checkout/issues/298#issuecomment-820748989 mentions a workaround of using `github.token` as a fallback.

**Comment by shiftkey** [comment]
Thanks @angela-tran for spotting that detail!

@teolemon I believe that what Angela has noted above is the constraint here - Dependabot doesn't have access to GitHub secrets by default.

As this problem is independent of this action I'm going to close this out as not something we can address in this project.

**Comment by teolemon** [comment]
@shiftkey it would probably be interesting to turn that into a documentation

**Comment by shiftkey** [comment]
> @shiftkey it would probably be interesting to turn that into a documentation

This does get mentioned in the [docs for workflow events on Actions](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflows-in-forked-repositories):

<img width="764" src="https://user-images.githubusercontent.com/359239/167719662-99257fbc-316d-410b-bdfa-1e3fe2cab844.png">

If you wanted to add some notes to the README about this and link off to those docs I'd happily review and help author the words...
